### ISSUE TITLE
Failed to read message type

### ISSUE THREAD

**Issue by slomkowski** [cornejo/libmumble#1]
I've started playing with the library. I am glad the example code is so clear. However I've noticed the following error occurring every time after 1-2 min: 

```
Failed to read message type
Error getting message: -1
Done
```
I am connecting to the remote Murmur server protected by password. The version string is below:

```
<F>2015-07-08 18:21:45.757 murmurd -- 1.2.3-349-g315b5f5-2.2+deb7u2
```
The server log is as follows:

```
<W>2015-07-08 18:19:23.365 1 => <15:example_username(-1)> Timeout
<W>2015-07-08 18:19:23.498 1 => <15:example_username(-1)> Connection closed:  [-1]
```
I am not sure if it relevant, but the other client on the channel is Mumble 1.2.9. 

Could you give me idea what the problem might be? I am not familiar with Mumble protocol. Perhaps using your help I can fix it and send pull request.

**Comment by cornejo** [comment]
Interesting. The server connection seems to timeout. I haven't noticed that in my testing.

Have you modified the example code? You need to call mumble_tick very regularly otherwise the server thinks you've gone away. Based on your report it seems the server gets upset around the 1-2 minute mark. The official pdf documentation in the project suggests it needs to be every 30 seconds, and my example code attempts to do it every 20 seconds.

The other difference I've noted is that you're running 1.2.3, and I'm testing against 1.2.4. I'll try to setup a 1.2.3 murmur server to test against but hopefully the difference isn't significant.

So if you can confirm that your changes to the example code (if any) haven't affected the calls to mumble_tick I'll investigate further.

**Comment by slomkowski** [comment]
I'm basically running vanilla example code. The only modification was server password. The return value from *ssl_connection_read* is -110 = *GNUTLS_E_PREMATURE_TERMINATION*. When I use OpenSSL, the return value is 0.

**Comment by cornejo** [comment]
Hmm, I'm not sure where the problem lies. I've just installed murmur 1.2.3 and tested the example code. The output is below:

$ ./mumble_example_static localhost
I received a buffer of 1204 bytes!
Written to /tmp/cert
Version Callback: v1.2.3. 1.2.3/X11/Ubuntu 15.04
cryptsetup_callback
codecversion_callback
Obtained channel state
permissionquery_callback
userstate_callback
Welcome to this server
serverconfig_callback
Pong Good/Late/Lost 0/0/0
Pong Good/Late/Lost 0/0/0
Pong Good/Late/Lost 0/0/0
Pong Good/Late/Lost 0/0/0
... etc

Is your output similar? (apart from the version string)

If you're not seeing the Pong messages then the tick() isn't firing, which would cause your issue.

If you are seeing the Pong messages then I'd be inclined to think there was some other network issue at play causing connections to fail after some amount of time? In this event I'm wondering if a pcap would be useful - though the comms are encrypted so the best we could determine is if packets are being dropped and who (if anyone) is closing the connection first.

The other thing that might be worth checking is the server config. Are you able to setup a new/clean murmur install to determine if perhaps it's a server setting causing the connection to drop? If this is the problem it would be good to know so I can solve it in the client. I'm not all that familiar with the server options so it's possible there's something I'm not catering for.

**Comment by slomkowski** [comment]
I've made further research. I had run it in different configurations. The program will fail only if the other client is connected. Otherwise it works without issues for at least five minutes. I've noticed the failure happens approximately after 37 s of talking to the microphone constantly.

I've looked into documentation. It seems the audio stream has its own ping packet https://mumble-protocol.readthedocs.org/en/latest/voice_data.html#ping-packet Does your library support it? Maybe that is the case? If no, I'll probably implement it.

**Comment by cornejo** [comment]
Ahh, that's interesting. I've been been able to replicate your problem.

But first to answer your question, the documentation states 'If the client stops receiving replies to the UDP packets at some point or never receives the first one it should immediately start tunneling the voice communication through TCP' (Section 5.1 in the pdf, or https://mumble-protocol.readthedocs.org/en/latest/voice_data.html#udp-connectivity-checks) Therefore I assume the voice ping packets are only there to determine if the UDP channel is supported or whether it should switch to a TCP channel instead. I'd never implemented the UDP channel so I never thought to implement the ping packets.

The reason why the server disconnects the libmumble client is because it has stopped hearing from it. In my test cases I never had a client in the channel generate sound for a sustained period, therefore when 20 seconds of silence arises my client would send a ping and all will be well. But if there's a sustained amount of sound on the channel the client will stay quiet and the server will eventually kick it out. My bad, I failed to test this reasonable scenario.

The solution is to ensure the client sends a ping regularly, even when incoming data resets the 20 second activity timer.

Please test the submitted patch and let me know if it fixes your problem!

**Comment by slomkowski** [comment]
I confirm that with your path the problem doesn't occur. However I've noticed another application crash. It happens in, let's say, 4 of 5 runs. I'm not sure, but it probably happened before your fixes as well. The case:

* server is empty
* *mumble_example* joins the server
* original Mumble client joins the server
* *mumble_example* crashes

Application output:
```
I received a buffer of 1204 bytes!
Written to /tmp/cert
Version Callback: v1.2.4. 1.2.3-349-g315b5f5-2.2+deb7u2/X11/Debian GNU/Linux 7.8 (wheezy)
cryptsetup_callback
codecversion_callback
Obtained channel state
permissionquery_callback
userstate_callback
1CONNECT Mumble server
serverconfig_callback
userstate_callback
Error getting message: -1
Done
```

The server log:
```
<W>2015-07-09 13:46:25.718 1 => <17:(-1)> New connection: 178.27.129.189:39570
<W>2015-07-09 13:46:25.894 1 => <17:(-1)> Client version 1.2.3 (OS Unknown: OS Release Unknown)
<W>2015-07-09 13:46:26.028 1 => Starting voice thread
<W>2015-07-09 13:46:26.136 1 => <17:example_username(-1)> Authenticated

<W>2015-07-09 13:46:38.279 1 => <18:(-1)> New connection: 178.27.129.189:39571
<W>2015-07-09 13:46:38.546 1 => <18:(-1)> Client version 1.2.9 (X11: 1.2.9)
<W>2015-07-09 13:46:38.663 1 => <18:slomkowski(-1)> Authenticated
<W>2015-07-09 13:46:38.830 1 => <17:example_username(-1)> Requesting crypt-nonce resync
<W>2015-07-09 13:46:38.980 1 => <17:example_username(-1)> Connection closed: The remote host closed the connection [1]
```

**Comment by cornejo** [comment]
My apologies. It seems that I haven't tested for many real world situations.

The issue was that the server would request a crypto-nonce resync when a new user joins the channel (not quite sure why, but ok). The request for a resync is done by sending a zero length message with the 'crypto' type. My code had apparently never previously attempted to read a zero length message, and hence fails.

I've since patched the code. Try it again.

**Comment by slomkowski** [comment]
Thanks. It works now.

BTW. I am going to add Opus codec to your library. Do you accept pull requests? Do you have any vision concerning it? My idea is to add *mumble_raw_audio_callback_t* and *mumble_send_raw_audio_data*. They will simply encode/decode raw audio using Opus. In this case, *mumble_audio_callback_t* callback would be called only if the incoming packet is not in Opus format.

**Comment by cornejo** [comment]
Sounds good to me. It's something I never got around to doing. I haven't given it any thought so implement it the way you like and I'll give it a look ito.

I'll gladly accept pull requests if they extend functionality.
